# @see https://docs.gitlab.com/ee/ci/README.html

# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

# 暂时只配置 build stage
stages:
  - build

build:
  stage: build
  script:
    - npm i
    - npm run lint
    - npm run test
    - npm run docs:build
  only:
    - master
