language: node_js

node_js:
  - 10.14.2

before_install: git fetch --depth=1000

install:
  - npm i

cache: npm

script:
  - npm run lint
  - npm run docs:build

# @see https://docs.travis-ci.com/user/deployment/pages/
deploy:
  provider: pages
  local-dir: docs/.vuepress/dist
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master

deploy:
  provider: npm
  email: bqliu@iflytek.com
  api_key: $NPM_TOKEN

notifications:
  email:
    recipients:
      - bqliu@iflytek.com
